/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.AnalizadorLexico.AnalizadorLexico;
import BackEnd.AnalizadorLexico.SubirArchivos;
import BackEnd.AnalizadorLexico.TipoToken;
import BackEnd.AnalizadorSintactico.AnalizadorSintactico;
//import static BackEnd.AnalizadorSintactico.AnalizadorSintactico.imprimirTabla;
import BackEnd.AnalizadorSintactico.Bloques;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SELVYN
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubirArchivo = new javax.swing.JButton();
        btndetectar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaReporte = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaSintactico = new javax.swing.JTable();
        NombreAnalizadorSintactico = new javax.swing.JLabel();
        NombreDelEditor = new javax.swing.JLabel();
        NombreAnalizadorLexico = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLineas = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextPane();
        btnSintactico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubirArchivo.setBackground(new java.awt.Color(0, 204, 204));
        btnSubirArchivo.setText("Subir ");
        btnSubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 90, 30));

        btndetectar.setBackground(new java.awt.Color(0, 204, 204));
        btndetectar.setText("Analizador Lexico ");
        btndetectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetectarActionPerformed(evt);
            }
        });
        jPanel1.add(btndetectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 120, 50));

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 204));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 90, 30));

        TablaReporte.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        TablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token", "Lexema", "Fila", "Columna"
            }
        ));
        jScrollPane5.setViewportView(TablaReporte);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 770, 220));

        TablaSintactico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Respuesta", "Lexema", "Error", "Fila", "Columna"
            }
        ));
        jScrollPane2.setViewportView(TablaSintactico);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 710, 280));

        NombreAnalizadorSintactico.setBackground(new java.awt.Color(255, 255, 255));
        NombreAnalizadorSintactico.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        NombreAnalizadorSintactico.setForeground(new java.awt.Color(153, 255, 0));
        NombreAnalizadorSintactico.setText("Analizador Sintactico");
        NombreAnalizadorSintactico.setToolTipText("");
        jPanel1.add(NombreAnalizadorSintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 240, -1));

        NombreDelEditor.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        NombreDelEditor.setForeground(new java.awt.Color(255, 255, 255));
        NombreDelEditor.setText("PARSER-PY");
        jPanel1.add(NombreDelEditor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        NombreAnalizadorLexico.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        NombreAnalizadorLexico.setForeground(new java.awt.Color(255, 255, 255));
        NombreAnalizadorLexico.setText("Analizador Lexico ");
        jPanel1.add(NombreAnalizadorLexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 200, 30));

        txtLineas.setFont(new java.awt.Font("Showcard Gothic", 2, 14)); // NOI18N
        jScrollPane3.setViewportView(txtLineas);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 40, 280));

        txtArchivo.setFont(new java.awt.Font("Showcard Gothic", 2, 14)); // NOI18N
        jScrollPane4.setViewportView(txtArchivo);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 720, 280));

        btnSintactico.setText("Analizador Sintactico");
        btnSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintacticoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 140, 50));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Decoracion/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirArchivoActionPerformed
        // TODO add your handling code here:
        SubirArchivos ar = new SubirArchivos();
        ar.AgregarArchivo();
    }//GEN-LAST:event_btnSubirArchivoActionPerformed

    private void btndetectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetectarActionPerformed
        // TODO add your handling code here:
        AnalizadorLexico lex = new AnalizadorLexico();
        lex.Analizar();
    }//GEN-LAST:event_btndetectarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtArchivo.setText("");
        txtLineas.setText("");
        AnalizadorLexico in = new AnalizadorLexico();
        in.limpiarTabla((DefaultTableModel) TablaSintactico.getModel());
        in.limpiarTabla((DefaultTableModel) TablaReporte.getModel());
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintacticoActionPerformed
        DefaultTableModel tablaModel = new DefaultTableModel();  // Crea y configura una instancia de DefaultTableModel

// Luego, crea una instancia de AnalizadorSintactico
        AnalizadorSintactico analizador = new AnalizadorSintactico();

// Supongamos que tienes una lista de tokens llamada 'tokensList'
        List<TipoToken> tokensList = new ArrayList<>();  // Asegúrate de llenar esta lista con tus tokens

// Llama al método analizarTokens
        List<Bloques> listaSimbolos = analizador.analizarTokens(tokensList, tablaModel);

    }//GEN-LAST:event_btnSintacticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreAnalizadorLexico;
    private javax.swing.JLabel NombreAnalizadorSintactico;
    private javax.swing.JLabel NombreDelEditor;
    public static javax.swing.JTable TablaReporte;
    public static javax.swing.JTable TablaSintactico;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSintactico;
    private javax.swing.JButton btnSubirArchivo;
    private javax.swing.JButton btndetectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextPane txtArchivo;
    public static javax.swing.JTextPane txtLineas;
    // End of variables declaration//GEN-END:variables
}
