/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases2.SubirArchivo;


/**
 *
 * @author SELVYN
 */
public class GenerarGrafico extends javax.swing.JFrame {

    /**
     * Creates new form GenerarGrafico
     */
    public GenerarGrafico() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visual = new javax.swing.JLabel();
        btnID = new javax.swing.JButton();
        btnConstante = new javax.swing.JButton();
        btnComparacion = new javax.swing.JButton();
        btnAritmetico = new javax.swing.JButton();
        btnAsignacion = new javax.swing.JButton();
        btnComentarios = new javax.swing.JButton();
        btnCadena = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnOtros = new javax.swing.JButton();
        btnReservadas = new javax.swing.JButton();
        CBPalabras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        GenerarGrafico = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Acerca = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Visual.setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().add(Visual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 990, 500));

        btnID.setText("Identificador ");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 40));

        btnConstante.setBackground(new java.awt.Color(255, 51, 51));
        btnConstante.setText("Constante");
        btnConstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnConstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 40));

        btnComparacion.setBackground(new java.awt.Color(0, 255, 255));
        btnComparacion.setText("Comparacion");
        btnComparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnComparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        btnAritmetico.setBackground(new java.awt.Color(0, 255, 255));
        btnAritmetico.setText("Aritmetico");
        btnAritmetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAritmeticoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAritmetico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 30));

        btnAsignacion.setBackground(new java.awt.Color(0, 255, 255));
        btnAsignacion.setText("Asignacion");
        btnAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, 30));

        btnComentarios.setBackground(new java.awt.Color(204, 204, 204));
        btnComentarios.setText("Comentarios");
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 30));

        btnCadena.setBackground(new java.awt.Color(255, 153, 102));
        btnCadena.setText("Cadena");
        btnCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadenaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 30));

        jButton5.setText("Aritmetico");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 30));

        btnOtros.setBackground(new java.awt.Color(51, 255, 0));
        btnOtros.setText("Otros");
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, 30));

        btnReservadas.setBackground(new java.awt.Color(204, 0, 255));
        btnReservadas.setText("Palabras Reservadas");
        btnReservadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservadasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, -1));

        CBPalabras.setBackground(new java.awt.Color(204, 0, 204));
        CBPalabras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "and", "as", "assert", "break", "class", "continue", "def", "del", "elif", "else", "except", "False", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try", "while", "whith", "yield" }));
        getContentPane().add(CBPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 50, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Decoracion/kali-mr-robot-augmented-reality-game-1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        Archivo.setText("Archivo ");
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Archivo.add(jMenuItem1);

        jMenuBar1.add(Archivo);

        GenerarGrafico.setText("Generar Grafico");

        jMenuItem2.setText("Generar_Grafico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        GenerarGrafico.add(jMenuItem2);

        jMenuBar1.add(GenerarGrafico);

        Ayuda.setText("Ayuda");

        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Ayuda.add(jMenuItem3);

        jMenuBar1.add(Ayuda);

        Acerca.setText("Acerca de ");

        jMenuItem4.setText("Acerca De");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Acerca.add(jMenuItem4);

        jMenuBar1.add(Acerca);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Archivo ventana = new Archivo();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed

    }//GEN-LAST:event_ArchivoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GenerarGrafico ventana = new GenerarGrafico();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ayuda ventana = new Ayuda();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Acerca ventana = new Acerca();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
        String imagePath1 = "Diagramas/ID.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath1);

    }//GEN-LAST:event_btnIDActionPerformed

    private void btnConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstanteActionPerformed
        // TODO add your handling code here:
        String imagePath2 = "Diagramas/Constantes.png";
        SubirArchivo on = new SubirArchivo();
        on.CargarImagenAutomata(imagePath2);
    }//GEN-LAST:event_btnConstanteActionPerformed

    private void btnAritmeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAritmeticoActionPerformed
        // TODO add your handling code here:
        String imagePath3 = "Diagramas/Aritmeticos.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath3);
    }//GEN-LAST:event_btnAritmeticoActionPerformed

    private void btnAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionActionPerformed
        // TODO add your handling code here:
        String imagePath4 = "Diagramas/Asignacion.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath4);
    }//GEN-LAST:event_btnAsignacionActionPerformed

    private void btnComparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparacionActionPerformed
        // TODO add your handling code here:
        String imagePath5 = "Diagramas/Comparaciones.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath5);
    }//GEN-LAST:event_btnComparacionActionPerformed

    private void btnCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadenaActionPerformed
        // TODO add your handling code here:
        String imagePath6 = "Diagramas/Cadena.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath6);
    }//GEN-LAST:event_btnCadenaActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed
        // TODO add your handling code here:
        String imagePath7 = "Diagramas/Otros.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath7);
    }//GEN-LAST:event_btnOtrosActionPerformed

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        // TODO add your handling code here:
        String imagePath8 = "Diagramas/Comentarios.png";
        SubirArchivo min = new SubirArchivo();
        min.CargarImagenAutomata(imagePath8);
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void btnReservadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservadasActionPerformed
        // TODO add your handling code here:
       String operadorSeleccionado = CBPalabras.getSelectedItem().toString();
       SubirArchivo min = new SubirArchivo();
       min.CargarImagenes(operadorSeleccionado);
    }//GEN-LAST:event_btnReservadasActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarGrafico.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarGrafico.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarGrafico.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarGrafico.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acerca;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JComboBox<String> CBPalabras;
    private javax.swing.JMenu GenerarGrafico;
    public static javax.swing.JLabel Visual;
    private javax.swing.JButton btnAritmetico;
    private javax.swing.JButton btnAsignacion;
    private javax.swing.JButton btnCadena;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btnComparacion;
    private javax.swing.JButton btnConstante;
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnOtros;
    private javax.swing.JButton btnReservadas;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
