/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases2.SubirArchivo;
import Clases2.AnalizadorLexico;
import static Clases2.AnalizadorLexico.analizarLexemas;
import Clases2.ColorTabla;
import Clases2.ColorTexto;
import Clases2.Patrones;
import Clases2.Token;
import java.awt.Color;
import java.util.List;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SELVYN
 */
public class Archivo extends javax.swing.JFrame {

    ColorTexto tex = new ColorTexto();
    /**
     * Creates new form Archivo
     */
    //ColorTabla colortabla = new ColorTabla();
    public Archivo() {

        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //TablaReporte.setDefaultRenderer(TablaReporte.getColumnClass(0), colortabla);
        this.TablaReporte.setDefaultRenderer(Object.class, new ColorTabla());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        btnSubirArchivo1 = new javax.swing.JButton();
        btnDetectar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaReporte = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextPane();
        btnColorTexto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaErrores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        GenerarGrafico = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Acerca = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 80, 60));

        btnSubirArchivo1.setText("Subir");
        btnSubirArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirArchivo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubirArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 80, 60));

        btnDetectar.setText("Detectar");
        btnDetectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 100, 50));

        TablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Token", "Lexema", "Patron", "Fila", "Columna"
            }
        ));
        jScrollPane5.setViewportView(TablaReporte);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 220));

        jScrollPane3.setViewportView(txtArchivo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 310));

        btnColorTexto.setText("Color");
        btnColorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorTextoActionPerformed(evt);
            }
        });
        getContentPane().add(btnColorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 100, 30));

        TablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Errores"
            }
        ));
        jScrollPane1.setViewportView(TablaErrores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 347, 450, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Decoracion/kali-mr-robot-augmented-reality-game-1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        Archivo.setText("Archivo ");
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Archivo.add(jMenuItem1);

        jMenuBar1.add(Archivo);

        GenerarGrafico.setText("Generar Grafico");

        jMenuItem2.setText("Generar_Grafico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        GenerarGrafico.add(jMenuItem2);

        jMenuBar1.add(GenerarGrafico);

        Ayuda.setText("Ayuda");

        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Ayuda.add(jMenuItem3);

        jMenuBar1.add(Ayuda);

        Acerca.setText("Acerca de ");

        jMenuItem4.setText("Acerca De");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Acerca.add(jMenuItem4);

        jMenuBar1.add(Acerca);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Archivo ventana = new Archivo();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed

    }//GEN-LAST:event_ArchivoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GenerarGrafico ventana = new GenerarGrafico();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ayuda ventana = new Ayuda();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Acerca ventana = new Acerca();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtArchivo.setText("");
        AnalizadorLexico in = new AnalizadorLexico();
        in.limpiarTabla((DefaultTableModel) TablaErrores.getModel());
        in.limpiarTabla((DefaultTableModel) TablaReporte.getModel());
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSubirArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirArchivo1ActionPerformed
        // TODO add your handling code here:
        SubirArchivo arch = new SubirArchivo();
        arch.AgregarArchivo();
    }//GEN-LAST:event_btnSubirArchivo1ActionPerformed

    private void btnDetectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectarActionPerformed
        // TODO add your handling code here:
        String texto = txtArchivo.getText();
        List<Clases2.Token> tokens = AnalizadorLexico.analizarLexemas(texto);
        
        for (Clases2.Token token : tokens) {
            Object[] rowData = {
                token.getTipo(),
                token.getLexema(),
                token.getPatron(),
                token.getFila(),
                token.getColumnaInicio()
            };
            DefaultTableModel model = (DefaultTableModel) TablaReporte.getModel();
            model.addRow(rowData);
        }

    }//GEN-LAST:event_btnDetectarActionPerformed

    private void btnColorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorTextoActionPerformed
        // TODO add your handling code here:
        tex.colorearEditorTexto(txtArchivo);
    }//GEN-LAST:event_btnColorTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acerca;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu GenerarGrafico;
    public static javax.swing.JTable TablaErrores;
    public static javax.swing.JTable TablaReporte;
    private javax.swing.JButton btnColorTexto;
    private javax.swing.JButton btnDetectar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSubirArchivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextPane txtArchivo;
    // End of variables declaration//GEN-END:variables
}
